name: Deploy to Railway and Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Create .env file
      run: |
        cat > .env << EOF
        RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
        HF_TOKEN=${{ secrets.HF_TOKEN }}
        HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
        REPO_NAME=${GITHUB_REPOSITORY#*/}
        EOF

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install huggingface_hub python-dotenv

    - name: Deploy to Railway
      uses: railway-org/action@v1
      with:
        token: ${{ secrets.RAILWAY_TOKEN }}

    - name: Deploy to Hugging Face
      run: |
        python deploy_hf.py